# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Sunstone
  module Docs
    module A_GETTING_STARTED
      # # Getting Started & System Overview
      #
      # Welcome to the documentation guide. This project utilizes Jasper to author
      # structured guides and compile them into native Crystal API documentation.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Introduction & Architecture</strong></td>
      #       <td><code>.topic_01_introduction</code></td>
      #       <td>Fundamental architectural principles and layout.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - shard.yml
      # - src/
      #
      module OVERVIEW
        # **Introduction & Architecture**: Fundamental architectural principles and layout.
        #
        # This section introduces the foundational concepts of the codebase.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Component</th>
        #       <th>Location</th>
        #       <th>Role</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>Core</td>
        #       <td>`src/`</td>
        #       <td>Main application logic</td>
        #     </tr>
        #     <tr>
        #       <td>Specs</td>
        #       <td>`spec/`</td>
        #       <td>Test suites</td>
        #     </tr>
        #     <tr>
        #       <td>Docs</td>
        #       <td>`docs_src/`</td>
        #       <td>Jasper source guides</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Command Options & Flags
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Flag / Option</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><code>--release</code></td>
        #       <td>Enables release optimizations.</td>
        #     </tr>
        #     <tr>
        #       <td><code>--verbose</code></td>
        #       <td>Enables verbose logging.</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # # Basic usage example
        # puts "Hello from Jasper-documented shard!"
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Always keep docs_src updated when modifying public APIs.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: How do I build the documentation site?**
        #   A: Run 'jasper build' followed by 'crystal docs'.
        #
        def self.topic_01_introduction : Nil; end
      end
    end
  end
end
{% end %}
