# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Sunstone
  module Docs
    module C_THEMING
      # # Authoring Custom Themes
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>1. Scaffolding a Custom Theme</strong></td>
      #       <td><code>.topic_01_scaffolding</code></td>
      #       <td>Generating boilerplate theme files with sunstone new-theme.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>2. The CSS Custom Properties Contract</strong></td>
      #       <td><code>.topic_02_variable_contract</code></td>
      #       <td>The core design tokens that all Sunstone themes must implement.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>3. Semantic Data-Attribute Selectors</strong></td>
      #       <td><code>.topic_03_data_attributes</code></td>
      #       <td>Targeting layout states and density without inline styles.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>4. Window Header Chrome & Visual Flow</strong></td>
      #       <td><code>.topic_04_pseudo_chrome</code></td>
      #       <td>Styling semantic window dots and architectural flow arrows in CSS.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      module AuthoringCustomThemes
        # **1 Scaffolding a Custom Theme**: Generating boilerplate theme files with sunstone new-theme.
        #
        # To create a new custom theme for your company or brand, run:
        #
        # ```bash
        # sunstone new-theme corporate --dir themes
        # ```
        #
        # This creates two companion files:
        # - `themes/corporate.css`: Base stylesheet implementing the `--sunstone-*` variable contract and component rules.
        # - `themes/corporate_palettes.json`: Palette catalog providing dark and light variants for per-slide switching.
        #
        # To activate your custom theme, update `deck.yml`:
        #
        # ```yaml
        # title: "Quarterly Strategy Review"
        # theme: "./themes/corporate.css"
        # ```
        #
        def self.topic_01_scaffolding : Nil; end

        # **2 The CSS Custom Properties Contract**: The core design tokens that all Sunstone themes must implement.
        #
        # Sunstone layouts communicate with themes through a flat CSS Custom Properties contract.
        # Your theme stylesheet should define these variables inside `:root`:
        #
        # ```css
        # :root {
        #   /* Typography */
        #   --sunstone-font-sans: 'Inter', system-ui, sans-serif;
        #   --sunstone-font-mono: 'JetBrains Mono', Consolas, monospace;
        #
        #   /* Geometry & Radii */
        #   --sunstone-radius-sm: 6px;
        #   --sunstone-radius-md: 10px;
        #   --sunstone-radius-lg: 16px;
        #   --sunstone-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.4);
        #
        #   /* Default Palette Tokens */
        #   --sunstone-bg: #0f172a;
        #   --sunstone-surface: #1e293b;
        #   --sunstone-surface-hover: #273549;
        #   --sunstone-text-primary: #f8fafc;
        #   --sunstone-text-secondary: #cbd5e1;
        #   --sunstone-text-muted: #94a3b8;
        #   --sunstone-accent: #38bdf8;
        #   --sunstone-accent-secondary: #818cf8;
        #   --sunstone-accent-tertiary: #34d399;
        #   --sunstone-border: #334155;
        #   --sunstone-border-active: #38bdf8;
        #   --sunstone-code-bg: #090d16;
        # }
        # ```
        #
        def self.topic_02_variable_contract : Nil; end

        # **3 Semantic Data-Attribute Selectors**: Targeting layout states and density without inline styles.
        #
        # Sunstone never injects `style="..."` on HTML elements.
        # Instead, themes style different states using data attributes:
        #
        # - `[data-layout="two-column"]`: Target specific layout structures.
        # - `[data-ratio="3:2"]`: Control grid proportions between columns.
        # - `[data-density="compact"]`: Reduce paddings, font sizes, and line heights for content-dense slides.
        # - `[data-color="accent|emerald|amber|crimson"]`: Style card accent colors dynamically.
        # - `[data-slot="left|right"]`: Style specific column positions.
        #
        def self.topic_03_data_attributes : Nil; end

        # **4 Window Header Chrome & Visual Flow**: Styling semantic window dots and architectural flow arrows in CSS.
        #
        # Sunstone code and terminal windows emit semantic `.terminal-dots` that can be shaped, tinted, or hidden per theme:
        #
        # ```css
        # .terminal-dots {
        #   display: inline-flex;
        #   gap: 6px;
        # }
        # .terminal-dot.red    { background-color: #ff5f56; }
        # .terminal-dot.yellow { background-color: #ffbd2e; }
        # .terminal-dot.green  { background-color: #27c93f; }
        # ```
        #
        # Flow arrows between architectural tiers use `.arch-tier + .arch-tier::before { content: "▼"; }`.
        #
        def self.topic_04_pseudo_chrome : Nil; end
      end
    end
  end
end
{% end %}
