# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Sunstone
  module Docs
    module GENERAL
      # # Themes & Theme-Scoped Palettes
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Built-In Themes</strong></td>
      #       <td><code>.topic_01_themes_overview</code></td>
      #       <td>Differences between the generic and sol.vin themes.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Palette per Slide</strong></td>
      #       <td><code>.topic_02_palette_per_slide</code></td>
      #       <td>Switching palettes per slide without styling conflicts.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      module themes
        # **Built-In Themes**: Differences between the generic and sol.vin themes.
        #
        # Sunstone ships with two built-in themes:
        #
        # - **`generic` (Default):** Clean, modern, high-contrast engineering aesthetic. Employs 8 modern dark and light palettes (`slate_dark`, `clean_light`, `emerald_matrix`, `midnight_indigo`, `crimson_obsidian`, `sunset_amber`, `nordic_ice`, `cyber_neon`). Completely free of extraneous visual elements.
        # - **`sol.vin`:** Retro terminal and desktop-inspired theme. Employs 46 retro palettes (`spaces_98`, `warm_paper`, `neon_cyber`, `monokai`, etc.), renders an interactive 3D spinning isometric wireframe cube (`cube.js`), and includes SVG chromatic color-matrix filters for emojis.
        #
        def self.topic_01_themes_overview : Nil; end

        # **Palette per Slide**: Switching palettes per slide without styling conflicts.
        #
        # Every slide can specify `palette: <id>`.
        # Sunstone compiles CSS definitions for each palette in the theme:
        #
        # ```css
        # .slide[data-palette="slate_dark"] {
        #   --sunstone-bg: #0f172a;
        #   --sunstone-surface: #1e293b;
        #   --sunstone-accent: #38bdf8;
        #   --sunstone-text-primary: #f8fafc;
        # }
        # ```
        #
        # When Reveal.js navigates between slides, the browser transitions colors instantly and smoothly without any DOM rewriting.
        #
        def self.topic_02_palette_per_slide : Nil; end
      end
    end
  end
end
{% end %}
