# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Sunstone
  module Docs
    module GENERAL
      # # Zero Inline Styles Architecture
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>How Zero-Inline-Styles Works</strong></td>
      #       <td><code>.topic_01_architecture</code></td>
      #       <td>Mapping semantic attributes to CSS grid and flex rules.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Chrome via CSS Pseudo-Elements</strong></td>
      #       <td><code>.topic_02_pseudo_elements</code></td>
      #       <td>Rendering window controls and arrows without extra HTML.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      module zero_inline_styles
        # **How Zero-Inline-Styles Works**: Mapping semantic attributes to CSS grid and flex rules.
        #
        # Rather than injecting `style="grid-template-columns: 3fr 2fr;"` into HTML tags, Sunstone emits semantic data attributes:
        #
        # ```html
        # <div class="slide-body" data-ratio="3:2" data-density="compact">
        # ```
        #
        # In `sunstone-base.css`, attribute selectors map directly to CSS grid definitions:
        #
        # ```css
        # [data-ratio="3:2"] {
        #   grid-template-columns: 3fr 2fr;
        # }
        # ```
        #
        def self.topic_01_architecture : Nil; end

        # **Chrome via CSS Pseudo-Elements**: Rendering window controls and arrows without extra HTML.
        #
        # Terminal dots and window controls are rendered purely with `::before` and box shadows:
        #
        # ```css
        # .window-header::before {
        #   content: "";
        #   display: inline-block;
        #   width: 10px;
        #   height: 10px;
        #   border-radius: 50%;
        #   background: #ff5f56;
        #   box-shadow: 15px 0 0 #ffbd2e, 30px 0 0 #27c93f;
        #   margin-right: 40px;
        # }
        # ```
        #
        # Flow arrows between architectural tiers use `.arch-tier + .arch-tier::before { content: "▼"; }`.
        #
        def self.topic_02_pseudo_elements : Nil; end
      end
    end
  end
end
{% end %}
