# ==============================================================================
# Sunstone::Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
module Sunstone
  # The `Sunstone::Docs` module is the authoritative technical reference and documentation guide.
  #
  # ## Learning Tracks & Topic Index
  #
  # The documentation is paced into 2 distinct tracks:
  #
  # ### 1. Getting started (`A_GETTING_STARTED`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>OVERVIEW</code></td>
  #       <td><strong>Getting Started & System Overview</strong></td>
  #       <td>Complete introduction to the architecture and core concepts.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 2. General (`GENERAL`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>introduction</code></td>
  #       <td><strong>Introduction to Sunstone</strong></td>
  #       <td>An overview of Sunstone, its architecture, and the philosophy of zero-inline-style presentations.</td>
  #     </tr>
  #     <tr>
  #       <td><code>quickstart</code></td>
  #       <td><strong>Quickstart Guide</strong></td>
  #       <td>Get started building and presenting slides with Sunstone in minutes.</td>
  #     </tr>
  #     <tr>
  #       <td><code>deck_manifest</code></td>
  #       <td><strong>Deck Manifest Specification</strong></td>
  #       <td>Comprehensive guide to authoring deck.yml and configuring presentation-wide settings.</td>
  #     </tr>
  #     <tr>
  #       <td><code>layouts</code></td>
  #       <td><strong>Semantic Slide Layouts</strong></td>
  #       <td>Catalog of all 15 semantic slide layouts supported by Sunstone.</td>
  #     </tr>
  #     <tr>
  #       <td><code>themes</code></td>
  #       <td><strong>Themes & Theme-Scoped Palettes</strong></td>
  #       <td>How Sunstone themes, palettes, and CSS custom properties work.</td>
  #     </tr>
  #     <tr>
  #       <td><code>zero_inline_styles</code></td>
  #       <td><strong>Zero Inline Styles Architecture</strong></td>
  #       <td>Technical guide to how Sunstone implements zero inline styles using semantic CSS and pseudo-elements.</td>
  #     </tr>
  #     <tr>
  #       <td><code>ci_cd</code></td>
  #       <td><strong>Continuous Integration & GitHub Pages</strong></td>
  #       <td>Automating slide compilation and web publishing via GitHub Actions.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  module Docs
    # **Quick-Start Commands**: Essential commands for building, running, and testing.
    #
    # #### Sunstone Commands:
    # ```bash
    # shards install
    # crystal spec
    # crystal docs
    # bin/sunstone --help
    # ```
    def self.topic_01_quick_start : Nil; end

    # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
    #
    # #### Structured Learning Tracks
    #
    # ##### 1. Getting started (`A_GETTING_STARTED`)
    # - `A_GETTING_STARTED::OVERVIEW`: **Getting Started & System Overview** &mdash; Complete introduction to the architecture and core concepts.
    #
    # ##### 2. General (`GENERAL`)
    # - `GENERAL::introduction`: **Introduction to Sunstone** &mdash; An overview of Sunstone, its architecture, and the philosophy of zero-inline-style presentations.
    # - `GENERAL::quickstart`: **Quickstart Guide** &mdash; Get started building and presenting slides with Sunstone in minutes.
    # - `GENERAL::deck_manifest`: **Deck Manifest Specification** &mdash; Comprehensive guide to authoring deck.yml and configuring presentation-wide settings.
    # - `GENERAL::layouts`: **Semantic Slide Layouts** &mdash; Catalog of all 15 semantic slide layouts supported by Sunstone.
    # - `GENERAL::themes`: **Themes & Theme-Scoped Palettes** &mdash; How Sunstone themes, palettes, and CSS custom properties work.
    # - `GENERAL::zero_inline_styles`: **Zero Inline Styles Architecture** &mdash; Technical guide to how Sunstone implements zero inline styles using semantic CSS and pseudo-elements.
    # - `GENERAL::ci_cd`: **Continuous Integration & GitHub Pages** &mdash; Automating slide compilation and web publishing via GitHub Actions.
    #
    def self.topic_02_reading_paths : Nil; end

    # **Master Table of Contents**: Complete hierarchical topic index.
    #
    # #### Complete Documentation Index
    #
    # ##### `A_GETTING_STARTED`
    # - `A_GETTING_STARTED::OVERVIEW`: **Getting Started & System Overview** &mdash; Complete introduction to the architecture and core concepts.
    #
    # ##### `GENERAL`
    # - `GENERAL::introduction`: **Introduction to Sunstone** &mdash; An overview of Sunstone, its architecture, and the philosophy of zero-inline-style presentations.
    # - `GENERAL::quickstart`: **Quickstart Guide** &mdash; Get started building and presenting slides with Sunstone in minutes.
    # - `GENERAL::deck_manifest`: **Deck Manifest Specification** &mdash; Comprehensive guide to authoring deck.yml and configuring presentation-wide settings.
    # - `GENERAL::layouts`: **Semantic Slide Layouts** &mdash; Catalog of all 15 semantic slide layouts supported by Sunstone.
    # - `GENERAL::themes`: **Themes & Theme-Scoped Palettes** &mdash; How Sunstone themes, palettes, and CSS custom properties work.
    # - `GENERAL::zero_inline_styles`: **Zero Inline Styles Architecture** &mdash; Technical guide to how Sunstone implements zero inline styles using semantic CSS and pseudo-elements.
    # - `GENERAL::ci_cd`: **Continuous Integration & GitHub Pages** &mdash; Automating slide compilation and web publishing via GitHub Actions.
    #
    def self.topic_03_table_of_contents : Nil; end

    # :nodoc:
    def self.quick_start : Nil; topic_01_quick_start; end
    # :nodoc:
    def self.reading_paths : Nil; topic_02_reading_paths; end
    # :nodoc:
    def self.table_of_contents : Nil; topic_03_table_of_contents; end
  end
end

require "./docs/general/introduction"
require "./docs/general/quickstart"
require "./docs/general/deck_manifest"
require "./docs/general/layouts"
require "./docs/general/themes"
require "./docs/general/zero_inline_styles"
require "./docs/general/ci_cd"
require "./docs/a_getting_started/overview"
{% end %}
