# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Sunstone
  module Docs
    module B_AUTHORING
      # # Deck Manifest Specification
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Structure of deck.yml</strong></td>
      #       <td><code>.topic_01_manifest_structure</code></td>
      #       <td>Root fields and global options in deck manifests.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Footer Template Tags</strong></td>
      #       <td><code>.topic_02_template_tags</code></td>
      #       <td>Dynamic placeholders available in footer strings.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      module DeckManifest
        # **Structure of deckyml**: Root fields and global options in deck manifests.
        #
        # The `deck.yml` file defines your presentation's identity, resolution, footer templates, theme, and slide sequence:
        #
        # ```yaml
        # title: "Building Microservices in Crystal"
        # subtitle: "Concurrency, Fiber Scheduling & Performance"
        # author: "Alex Morgan"
        # theme: "generic"
        # width: 1920
        # height: 1080
        #
        # footer_left: "☀️ {title}"
        # footer_center: "{author} • {palette}"
        # footer_right: "Slide {slide_num} / {total_slides}"
        #
        # slides:
        #   - slides/01_intro.yml
        #   - slides/02_architecture.yml
        #   - slides/03_benchmarks.yml
        #   - slides/04_closing.yml
        # ```
        #
        def self.topic_01_manifest_structure : Nil; end

        # **Footer Template Tags**: Dynamic placeholders available in footer strings.
        #
        # Footers support dynamic variable interpolation:
        # - `{title}`: Presentation title.
        # - `{subtitle}`: Presentation subtitle.
        # - `{author}`: Deck author name.
        # - `{palette}`: Human-readable name of the slide's active palette.
        # - `{palette_id}`: Technical identifier of the active palette.
        # - `{slide_num}`: Current slide number (1-indexed).
        # - `{total_slides}`: Total slide count in the entire presentation.
        # - `{slide_title}`: Current slide title.
        #
        def self.topic_02_template_tags : Nil; end
      end
    end
  end
end
{% end %}
